name: Running
on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 build_Linux:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3

  - name: Add GTest
    run: git clone https://github.com/google/googletest.git third-party/gtest -b release-1.11.0

  - name: Install lcov
    run: sudo apt-get install -y lcov

  - name: CMake banking and tests
    run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

  - name: Build B&T
    run: cmake --build ${{github.workspace}}/build
  
  - name: Run test
    run: ${{github.workspace}}/build/run_test
    
  - name: Do lcov stuff
    run: lcov -c -d ${{github.workspace}}/banking --include *.cpp --output-file ./coverage/lcov.info

  - name: Publish to coveralls.io
    uses: coverallsapp/github-action@v1.1.2
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
